title: PS기록
description: PS기록용 사이트 
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: https://ssa53.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
